version: '3'

services:
  nginx:
    container_name: "${APP_ENV}.${APP_NAME}.nginx"
    image: nginx:1.19
    restart: always
    ports:
      - "${EXPOSE_HTTP_PORT}:80"
    volumes:
      - ./:${APP_BASE_PATH}/
      - ./docker/nginx/templates:/etc/nginx/templates
    environment:
      - NGINX_HOST_PATH=${APP_BASE_PATH}/public/
      - NGINX_PHP_FPM_HOST=${APP_ENV}.${APP_NAME}.php-fpm

  php-fpm:
    container_name: "${APP_ENV}.${APP_NAME}.php-fpm"
    build: docker/php-fpm
    restart: always
    working_dir: ${APP_BASE_PATH}/
    volumes:
      - ./:${APP_BASE_PATH}/
    environment:
      - XDEBUG_CONFIG=enable=${XDEBUG_ENABLE} \
                       remote_enable=${XDEBUG_REMOTE_ENABLE} \
                       profiler_enable=${XDEBUG_PROFILER_ENABLE} \
                       remote_host=${XDEBUG_REMOTE_HOST} \
                       remote_port=${XDEBUG_REMOTE_PORT} \
                       remote_autostart=${XDEBUG_REMOTE_AUTOSTART} \
                       idekey=${XDEBUG_IDE_KEY} \
                       remote_connect_back=${XDEBUG_REMOTE_CONNECT_BACK}
      - PHP_IDE_CONFIG=serverName=laravel-excel-rabbitmq-redis-demo

  db:
    container_name: "${APP_ENV}.${APP_NAME}.db"
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql

  rabbitmq:
    container_name: "${APP_ENV}.${APP_NAME}.rabbitmq"
    image: bitnami/rabbitmq:3.8.9
    user: root
    ports:
      - '${EXPOSE_RABBITMQ_PORT}:5672'
      - '${EXPOSE_RABBITMQ_WEB_PORT}:15672'
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    volumes:
      - rabbitmq-data:/bitnami

  redis:
    container_name: "${APP_ENV}.${APP_NAME}.redis"
    image: 'bitnami/redis:5.0.8'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data

networks:
  default:
    external:
      name: ${APP_NETWORK_NAME}

volumes:
  redis-data:
  db-data:
  rabbitmq-data:
